export const CONFIG = {
  workshop: {
    title: "AI + Fullstack Project Workshop",
    dateTime: "02 May 2026 - 8 PM",
    showDateTime: true,
    duration: "1 Hour",
  },
  workshopLanguage: 'Tamil',
  whatsappNumber: '919790321115',
  googleSheetUrl: 'https://script.google.com/macros/s/AKfycbytCwl10G-1hEh2N7aQzdVsoxeurhl3s56wDXQ6WHAwQac3YP5racnASV_qC8oEtLghFA/exec',
  enquiryEmail: 'sales.aidigitalgen@gmail.com',
  plans: [
    {
      id: "standard",
      enabled: true,
      name: "Standard",
      originalPrice: 499,
      offerPrice: 0,
      badge: "🔥 FREE Today",
      highlight: true,
      description: "Beginners with zero coding",
      features: [
        { text: "1-hour live workshop", included: true },
        { text: "Build 1 simple AI website", included: true },
        { text: "1 month livecall + whatsapp", included: true },
        { text: "Tamil explanation & doubts", included: true },
        { text: "GitHub & Netlify Deployment", included: true },
        { text: "Free project guidance", included: true },
        { text: "Course Certificate", included: false },
        { text: "Resume + Placement support", included: false },
        { text: "AI agents creations", included: false },
        { text: "Digital Marketing basics", included: false },
        { text: "Lifetime community access", included: false },
        { text: "Latest Gen-AI Fullstack Stack", included: false },
        { text: "Freelance Client Acquisition", included: false },
        { text: "Advanced Cloud (AWS/Vercel)", included: false },
        { text: "Premium AI Tools & APIs", included: false },
         { text: "Google SEO analysis with real data", included: false },
        { text: "Multiple payment gateway integration", included: false }
      ]
    },
    {
      id: "premium",
      enabled: true,
      name: "Premium",
      originalPrice: 999,
      offerPrice: 499,
      badge: "⭐ Most Popular",
      highlight: true,
      description: "Become internship ready in 3 days",
      features: [
        { text: "3-day live training", included: true },
        { text: "Build 3 real-world projects", included: true },
        { text: "3-month livecall + whatsapp", included: true },
        { text: "Tamil explanation & doubts", included: true },
        { text: "GitHub & Netlify Deployment", included: true },
        { text: "Free hosting (6 months)", included: true },
        { text: "Course Certificate", included: true },
        { text: "Resume + Placement support", included: true },
        { text: "AI agents creations", included: true },
        { text: "Digital Marketing basics", included: true },
        { text: "Latest Gen-AI Fullstack Stack", included: true },
        { text: "Lifetime community access", included: false },
        { text: "Freelance Client Acquisition", included: false },
        { text: "Advanced Cloud (AWS/Vercel)", included: false },
        { text: "Premium AI Tools & APIs", included: false },
        { text: "Google SEO analysis with real data", included: false },
        { text: "Multiple payment gateway integration", included: false }
      ]
    },
    {
      id: "pro",
      enabled: true,
      name: "Pro",
      originalPrice: 4999,
      offerPrice: 2999,
      badge: "🚀 Best Value",
      highlight: true,
      description: "Job Support + Personal guidance",
      features: [
        { text: "1:1 personal mentorship", included: true },
        { text: "Build 10 industry projects", included: true },
        { text: "6-month livecall + whatsapp", included: true },
        { text: "Tamil explanation & guidance", included: true },
        { text: "GitHub & Netlify Deployment", included: true },
        { text: "Free hosting (1 year)", included: true },
        { text: "Course Certificate", included: true },
        { text: "Advanced Resume + Placement", included: true },
        { text: "AI agents building (advanced)", included: true },
        { text: "Digital Marketing professional", included: true },
        { text: "Latest Gen-AI Fullstack Stack", included: true },
        { text: "Lifetime community access", included: true },
        { text: "Freelance Client Acquisition", included: true },
        { text: "Advanced Cloud (AWS/Vercel)", included: true },
        { text: "Premium AI Tools & APIs", included: true },
        { text: "Google SEO analysis with real data", included: true },
        { text: "Multiple payment gateway integration", included: true }
      ]
    }
  ]
};
